---
- name: Ensures skydive configuration folder exists
  file:
    path: "{{ skydive_config_file | dirname }}"
    state: directory

- name: Create empty config file is needed
  copy:
    content: ""
    dest: "{{ skydive_config_file }}"
    mode: 0600
    force: no

- name: Set host ID
  yedit:
    src: "{{ skydive_config_file }}"
    key: host_id
    value: "{{ ansible_hostname }}"

- name: Set analyzers list
  yedit:
    src: "{{ skydive_config_file }}"
    key: analyzers
    value: "{{ analyzers.split(',') }}"

- name: Set flow protocol
  yedit:
    src: "{{ skydive_config_file }}"
    key: "flow.protocol"
    value: "{{ skydive_flow_protocol }}"

- name: Set extra config vars
  yedit:
    src: "{{ skydive_config_file }}"
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: "{{ skydive_extra_config }}"
  when: skydive_extra_config is defined
