---
- name: Install opstools repository
  package:
    name: https://buildlogs.centos.org/centos/7/opstools/x86_64/common/centos-release-opstools-1-4.el7.noarch.rpm
    state: present
  when: ansible_os_family == "RedHat"

- name: Install skydive package
  package:
    name: skydive
    state: present
