- package:
    name: "{{ item }}"
    state: present
  with_items:
     - ffmpeg
     - gifsicle
     - libvirt
     - vagrant-libvirt
     - virt-what
     - ansible
     - dnf-utils
     - manifest-tool
     - git-lfs

- service:
    name: libvirtd
    state: started
    enabled: yes

- include_tasks: virtualbox.yml
