---
- selinux:
    policy: targeted
    state: permissive

- shell: "dnf copr enable -y ganto/lxc3"

- package:
    name: lxc
    state: present

- package:
    name: lxd
    state: present

- lineinfile:
    path: /etc/subuid
    line: 'root:1000000:65536'

- lineinfile:
    path: /etc/subgid
    line: 'root:1000000:65536'

- service:
    name: lxd
    state: started
    enabled: yes

- file:
    src: /var/run/lxd.socket
    dest: /var/lib/lxd/unix.socket
    state: link

- shell: "systemctl enable lxd"

- shell: "lxd init --auto"
