name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache-dependency-path: go.sum

    - name: Install pcap
      run: sudo apt-get install -y libpcap0.8-dev

    - name: Build graffiti
      run: cd graffiti && go build -v ./...

    - name: Build
      run: go build -v ./...
